# Site wide configuration

title:            Blog of zouliping
locale:           en_CN
url:              http://echo.vars.me
url:              http://zouliping.github.io
url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Liping Zou
  avatar: avatar.png
  bio: "An Android Developer"
  email: zouliping007@gmail.com
  disqus-shortname: 
  twitter: ZouLiping
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: zouliping
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #zouliping007@163.com
  instagram: zouliping007
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
